---
title: "DMproject"
author: "Jason"
date: "March 21, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##########    Data Mining Project    ##########
#####  ---->>  EDA
######  Import Data
```{r}
creditcard=readXL("C:/Users/meiha/Desktop/17-S1/Data Mining/Project/default of credit card clients.xls",
         rownames=FALSE, header=TRUE, na="", sheet="Data", stringsAsFactors=TRUE)
attach(creditcard)
dim(creditcard)



```
######  Missing Value & changing data type
```{r}
# My part; Last 7 columns
a=creditcard[,-c(1:18)]
summary(a)
library(Amelia)
amelia(a) # all good here
# Overall data missing value check
amelia(creditcard)

# Change data type
summary(creditcard)
# names(creditcard)

creditcard[SEX=as.factor(SEX)]
EDUCATION=as.factor(EDUCATION)
MARRIAGE=as.factor(MARRIAGE)
summary(creditcard)
# Change the type of response variable
creditcard$DorND=as.factor(creditcard$default.payment.next.month)
summary(DorND)
```
######  Seperate Data
```{r}
# Generate 20000 random integer
g2000ri=sample(1:30000,20000)
length(g2000ri)

# set 20000 observations as our Training set
TraingSet=creditcard[g2000ri,]
# The rest 10000 observations as test set
TestSet=creditcard[-c(g2000ri),]
print("Dimension of Training Data Set")
dim(TraingSet)
print("Dimension of Test Data Set")
dim(TestSet)
```
######
```{r}

```
######
```{r}

```
######
```{r}

```

